### ISSUE TITLE
Implement spec events

### ISSUE THREAD

**Issue by gjermundgaraba** [cosmos/solidity-ibc-eureka#108]
As soon as the IBC Eureka events are finalized (https://github.com/cosmos/ibc/pull/1165) we need to do a full cleanup of the events we currently emit from our contracts.

We likely have some unnecessary events, so the initial plan here is to remove the current events and only implement the spec events. After that, we can decide if we need more events (and if those should also go into the spec).

**Comment by srdtrk** [comment]
1. Would multipayload only differ on ack events?
2. Maybe you can open a PR to remove unnecessary events? (I think we use some of those events in the tests but maybe you can come up with another way to test the same logic)

**Comment by sangier** [comment]
1. We would need to change `sendPacket` events too as in spec we emit a `send_payload` specific event in the multipayload case. 
2. Gonna check this out.

**Comment by gjermundgaraba** [comment]
Did a quick check on removing `emit ICS20Transfer(packetData, erc20Address);` and it looks like it saves about 5k of gas to do so. I would say that we should remove anything that is not needed as we are trying to squeeze out as much performance as we can, and if this is not strictly needed, we should just get rid of it.

**Comment by sangier** [comment]
Ok, agreed. Will remove the transfer events so!

**Comment by srdtrk** [comment]
Let's also remove any other unnecessary events
