### ISSUE TITLE
`just install-operator` fails when using the Rust stable release channel

### ISSUE THREAD

**Issue by rootulp** [cosmos/solidity-ibc-eureka#159]
## Context

On d952d312

## Problem

```
just install-operator

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/rootulp/.cargo/git/checkouts/union-ee564f669096b471/18c86b4/lib/unionlabs/src/lib.rs:13:1
   |
13 | #![feature(trait_alias)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```

## Proposal

To resolve I had to do:

```shell
rustup install nightly
rustup override set nightly
just install-operator
```

which worked

**Comment by srdtrk** [comment]
This was true in older commits of this repository, but since then, we removed union dependencies and should no longer require nightly. Our ci also fully runs on stable rust. Am I missing something?

**Comment by rootulp** [comment]
Oops nope, sorry I only tested on an older commit because I was trying to setup https://github.com/celestiaorg/celestia-zkevm-ibc-demo/ for local development and the commit of solidity-ibc-eureka is no longer accessible so I downgraded to the last known working version https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/17#issuecomment-2526702920

Can close this and the PR if it's resolved on main.
