### ISSUE TITLE
Change sdkCoin functions names to camelCase

### ISSUE THREAD

**Issue by sangier** [cosmos/solidity-ibc-eureka#32]
`_ERC20ToSdkCoin_ConvertAmount` and  `_SdkCoinToERC20_ConvertAmount` should be in camelCase format to account for standards used in libraries. So change to the name to `convertAmountERC20ToSdkCoin` and  `convertAmountSdkCoinToERC20` taking into account any place where they are used.

**Comment by MukulKolpe** [comment]
Hey @crodriguezvega, can I work on this one?

**Comment by crodriguezvega** [comment]
Hi @MukulKolpe. Yes, thank you! I will assign it to you.

**Comment by crodriguezvega** [comment]
Superseded by #55
