### ISSUE TITLE
Refactor IBCStore into a separate contract

### ISSUE THREAD

**Issue by srdtrk** [cosmos/solidity-ibc-eureka#71]
## Description

Currently, the IBCStore is implemented as an abstract contract and used by ICS26Router, which results in all state being stored directly in the ICS26Router contract. To improve modularity and future-proof our design, we should decouple the IBCStore from the ICS26Router. This separation will not only enhance the clarity of responsibilities between the router and the storage layer, but it will also facilitate easier contract migrations and upgrades in the future (see issue #12).

**Comment by sangier** [comment]
Hey guys, just seen that a new version of solidity "0.8.28" has been released and it introduces the "transient storage" concept which may be useful to save storage costs. Not really sure if this can be useful for this refactor, but it may be worth to check it out!  

[Ref](https://www.linkedin.com/feed/update/urn:li:activity:7249802241430196227/)
