### ISSUE TITLE
How to deal with union light client modifications

### ISSUE THREAD

**Issue by gjermundgaraba** [cosmos/solidity-ibc-eureka#90]
We have some small modifications to the union light client to make it work for our Solidity Eureka implementation.
The code we use for our e2e tests with those modifications are currently located in this branch: https://github.com/gjermundgaraba/union/tree/gjermund/eth-light-client-for-eureka

The changes are mostly around:
* Using Merkle path v2 (union will likely need to make this change themselves soon as well, so might not be an issue)
* TODO: Fill out the rest of the changes

The question is, where should those changes live? If possible, the ideal scenario might be that we upstream our changes to the union repo so that we don't have to maintain a fork, but if that is not possible, we need to consider where such a fork should live, and how to make the maintenance burden as light as possible.

**Comment by srdtrk** [comment]
We have decided to move the light client to ibc-go, therefore, I'm closing the issue
